mode: train
debug: False

components:
  data: train
  transform: vm
  system: vm
  model: vm

loss:
  loss: 1.0
  chamfer: 0.1
  p2plane: 0.05
  structure: 0.05

optimizer:
  __target__: adam
  lr: 0.0003
  weight_decay: 0.000001

trainer:
  epochs: 200
  grad_accum_steps: 2
  grad_clip_norm: 1.0
  ema_decay: 0.999
  warmup_epochs: 5
  lr_scheduler:
    __target__: cosine
    min_lr: 0.000001
  amp_level: 1  # <-- ENABLE AUTOMATIC MIXED PRECISION